### ISSUE TITLE
Why sftp instead of rsync?

### ISSUE THREAD

**Issue by bcardarella** [green-arrow/ember-cli-deploy-ssh-index#4]
I am looking to migrate away from ember-cli-deploy-ssh and after a review of this library I see you're using sftp instead of rsync. Any reason?

**Comment by green-arrow** [comment]
@bcardarella - The main reasons I went with `sftp` instead of `rsync` are:
- `sftp` tends to be installed by default on a larger number of Linux distros. I know it comes standard in Ubuntu, but I don't believe it is standard in distros like CentOS.
- I was already familiar with the `ssh2` library, which comes with `sftp`.
